### ISSUE TITLE
[BUG] House System not loading

### ISSUE THREAD

**Issue by Hiperinio** [qbcore-framework/qb-houses#46] opened 2021-09-25 10:54 UTC
Describe the bug
After a player buy the house and the server restart house system is not working.

To Reproduce
1. Install fresh QBCore via TxAdmin
2. Create house with realestate job, swap to another job and buy the house
3. Log out and restart the server
4. Spawn and tp to the house and try to enter the house.
5. You will get this error: https://i.imgur.com/bN65pxc.png

Questions (please complete the following information):

When you last updated: Just now, from TxAdmin
Are you using custom resource? which ones?: No
Have you renamed qb- to something custom?: No

**Comment by nick-strohm** [comment] 2021-09-25 16:38
Duplicate of #45

**Closed** 2021-10-01 06:39 UTC
