### ISSUE TITLE
BUGGED OUT WHEN BUYING HOUSE CANT REENTER

### ISSUE THREAD

**Issue by hoodz123** [qbcore-framework/qb-houses#48] opened 2021-09-26 01:27 UTC
Script Error @qb-houses/client/main.lua:573 attempt to index a nil value (upvalue 'data) Handler (@qb-houses/client/main.lua:53)

**Comment by nick-strohm** [comment] 2021-09-27 16:43
Duplicate of #45

**Closed** 2021-10-01 06:39 UTC
